Messed up installation order in README.md
wulkanowy/wulkanowy-web pull request #67
Opened 2021-06-06 19:05 UTC by SaviPrograms

Wrong order and working directory of `npm i`. Command misplaced in main directory, which doesn't contain package.json. Moved to last step, right before building frontend.

2021-06-06 19:14 UTC, MRmlik12 requested changes

2021-06-06 19:14 UTC, MRmlik12 commented on README.md
> +npm i
Please move `npm i` to previous line and change `npm i` to `npm i frontend`

2021-06-06 19:27 UTC, Pengwius commented
Hi, could you name commits in english? Advice for the future.

2021-06-07 08:17 UTC, MRmlik12 approved these changes
Nice

2021-06-07 08:20 UTC, Pengwius approved these changes
LGTM

2021-06-07 08:20 UTC, merged