Fix workflows
wulkanowy/wulkanowy-web pull request #82
Opened 2021-12-21 20:19 UTC by Zaptyp

This PR fix the workflows

2021-12-31 19:30 UTC, Pengwius requested changes

2021-12-31 19:30 UTC, Pengwius commented on .github/workflows/backend.yml
> +            pip install pytz
add this depandencies to requirements file

2021-12-31 19:42 UTC, Zaptyp commented on .github/workflows/backend.yml
> +            pip install pytz
Pytz is always added to the default pip instalation not need add to requirements file

2022-02-02 08:38 UTC, Pengwius approved these changes

2022-02-02 08:39 UTC, merged