Completely new backdend and reworked frontend by Marioneq
wulkanowy/wulkanowy-web pull request #93
Opened 2022-04-07 19:37 UTC by Zaptyp

This PR was created entirely by Marioneq. It has a completely rewritten backend and frontend. I only updated the workflows and made changes to README.md
#83

2022-04-24 10:12 UTC, Pengwius submitted a review, later dismissed

2022-04-24 10:12 UTC, Pengwius commented on backend/app/endpoints/login.py
> +def main(data: models.Login, response: Response):
Change function name to `login` or something like this

2022-04-24 10:12 UTC, Pengwius commented on backend/app/endpoints/login.py
> +            for student in students_response.json()["data"]:
Move loop body to other function to make code cleaner

2022-04-24 10:12 UTC, Pengwius commented on backend/app/paths.py
> +class UZYTKOWNIK:
Use english names here

2022-04-24 10:12 UTC, Pengwius commented on backend/app/endpoints/uonetplus_uczen.py
> +            is_religia_or_etyka=descriptive_grade["IsReligiaEtyka"],
Wtf is this name?

2022-04-24 10:24 UTC, Marioneq4958 commented on backend/app/paths.py
> +class UZYTKOWNIK:
ale to nazwy modułów vulcana

2022-04-24 10:26 UTC, Pengwius commented on backend/app/paths.py
> +class UZYTKOWNIK:
A co ci szkodzi ustawić w projekcie na polski?

2022-04-24 10:32 UTC, Marioneq4958 commented on backend/app/paths.py
> +class UZYTKOWNIK:
to mam to nazywać UONETPLUS-STUDENT, UONETPLUS-USER?

2022-04-24 10:33 UTC, Marioneq4958 commented on backend/app/endpoints/uonetplus_uczen.py
> +            is_religia_or_etyka=descriptive_grade["IsReligiaEtyka"],
a jak mam to nazwać?

2022-04-24 10:35 UTC, Pengwius commented on backend/app/endpoints/uonetplus_uczen.py
> +            is_religia_or_etyka=descriptive_grade["IsReligiaEtyka"],
is_religion_or_ethics

2022-04-24 10:36 UTC, Marioneq4958 commented on backend/app/endpoints/uonetplus_uczen.py
> +            is_religia_or_etyka=descriptive_grade["IsReligiaEtyka"],
ok

2022-04-25 14:53 UTC, Pengwius commented on backend/app/endpoints/login.py
> +            for student in students_response.json()["data"]:
Więc?

2022-04-25 14:56 UTC, Marioneq4958 commented on backend/app/endpoints/login.py
> +            for student in students_response.json()["data"]:
więc do tego ona służy

2022-04-25 14:59 UTC, Pengwius commented on backend/app/endpoints/login.py
> +            for student in students_response.json()["data"]:
Co ci szkodzi przenieść wnętrze tej pętli do innej funkcji? Bo teraz to nasrane tak tam jest, że nie wiadomo co to robi

2022-04-25 15:28 UTC, Marioneq4958 commented on backend/app/endpoints/login.py
> +            for student in students_response.json()["data"]:
Pokaż jak według ciebie ten plik ma wyglądać

2022-04-25 17:22 UTC, MRmlik12 submitted a review, later dismissed

2022-04-25 17:22 UTC, MRmlik12 commented on frontend/src/App.vue
> +    let dark_theme = localStorage.getItem('dark_theme');
use camel case variable names

2022-04-25 17:22 UTC, MRmlik12 commented on frontend/src/api.ts
> +    } catch (error: any) {
you can short to axios().then().catch()

2022-04-25 17:22 UTC, MRmlik12 commented on frontend/src/components/Login/SelectStudent.vue
> -    console.log(this.$store.state.loginData.data.students.data[0]);
remove console.log()

2022-04-25 17:22 UTC, MRmlik12 commented on frontend/src/components/Panel/AccountManager.vue
> +
Why are you add empty lines? please keep consistency in source code

2022-04-25 17:22 UTC, MRmlik12 commented on frontend/src/components/Panel/AppBar.vue
> +
Again empty lines

2022-04-25 17:22 UTC, MRmlik12 commented on frontend/src/store/index.ts
>    mutations: {
Please improve store file implementation

2022-04-25 17:27 UTC, Marioneq4958 commented on frontend/src/api.ts
> +    } catch (error: any) {
ok

2022-04-25 17:28 UTC, Marioneq4958 commented on frontend/src/App.vue
> +    let dark_theme = localStorage.getItem('dark_theme');
ok

2022-04-25 17:29 UTC, Marioneq4958 commented on backend/app/endpoints/login.py
> +def main(data: models.Login, response: Response):
ok

2022-04-25 18:54 UTC, Zaptyp commented on frontend/src/components/Login/SelectStudent.vue
> -    console.log(this.$store.state.loginData.data.students.data[0]);
WTF was never in that file. 
NOTE: Check carefully what you are checking

2022-05-08 14:09 UTC, Zaptyp commented on backend/app/paths.py
> +class UZYTKOWNIK:
Użyj tych co napisałeś i zamknij

2022-05-08 14:11 UTC, Marioneq4958 commented on backend/app/paths.py
> +class UZYTKOWNIK:
źle to by wyglądało, a po za tym są to skróty url'ów więc nie powinno się tego tłumaczyć

2022-05-08 14:15 UTC, Zaptyp commented on backend/app/endpoints/login.py
> +            for student in students_response.json()["data"]:
Zamykam z powodu braku aktywności

2022-05-21 23:53 UTC, MarcinK50 requested changes
Please make tests cleaner (spaghetti code)

2022-05-21 23:53 UTC, MarcinK50 commented on backend/test.py
> +        == "Litwo! Ojczyzno moja! Ty jesteś jak zdrowie. Ile cię trzeba cenić, ten tylko aż kędy pieprz rośnie gdzie podział się? szukać prawodawstwa."
CHANGE THIS PLEASE

2022-05-22 07:12 UTC, Zaptyp commented on backend/test.py
> +        == "Litwo! Ojczyzno moja! Ty jesteś jak zdrowie. Ile cię trzeba cenić, ten tylko aż kędy pieprz rośnie gdzie podział się? szukać prawodawstwa."
Ok done

2022-05-22 18:55 UTC, MarcinK50 approved these changes
niech ci będzie

2022-05-22 19:00 UTC, merged